### ISSUE TITLE
Can't create database

### ISSUE THREAD

**Issue by rbicelli** [anklimsk/wpkg-express-2#12]
Hi, I tried configuring the app, but I'm unable to create database, it creates a single table then nothing else:

```
Creating database and initializing data
---------------------------------------------------------------
Create schema of application
---------------------------------------------------------------
Are you sure you want to drop the table(s)? (y/n)
[n] > y
Are you sure you want to create the table(s)? (y/n)
[y] > y
Error: Table queued_tasks for model ExtendQueuedTask was not found in datasource default.
#0 /var/www/wpkg/lib/Cake/Model/Model.php(3686): Model->setSource('queued_tasks')
#1 /var/www/wpkg/app/Model/AppModel.php(135): Model->getDataSource()
#2 /var/www/wpkg/app/Model/AppModel.php(150): AppModel->_getDataSourceName()
#3 /var/www/wpkg/app/Model/ExtendQueuedTask.php(47): AppModel->isDataSourceMysql()
#4 [internal function]: ExtendQueuedTask->__construct(Array)
#5 /var/www/wpkg/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#6 /var/www/wpkg/app/Model/Behavior/GroupActionBehavior.php(65): ClassRegistry::init('ExtendQueuedTas...')
#7 /var/www/wpkg/lib/Cake/Model/BehaviorCollection.php(145): GroupActionBehavior->setup(Object(Archive), Array)
#8 /var/www/wpkg/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load('GroupAction', Array)
#9 /var/www/wpkg/lib/Cake/Model/Model.php(781): BehaviorCollection->init('Archive', Array)
#10 /var/www/wpkg/app/Plugin/Shim/Model/ShimModel.php(26): Model->__construct(Array, NULL, NULL)
#11 [internal function]: ShimModel->__construct(Array)
#12 /var/www/wpkg/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#13 /var/www/wpkg/app/Plugin/CakeInstaller/Model/InstallerInit.php(52): ClassRegistry::init('Archive', true)
#14 /var/www/wpkg/app/Config/Schema/schema.php(60): InstallerInit->initDbTable('archives')
#15 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(448): AppSchema->after(Array)
#16 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(351): SchemaShell->_run(Array, 'create', Object(AppSchema))
#17 /var/www/wpkg/lib/Cake/Console/Command/SchemaShell.php(250): SchemaShell->_create(Object(AppSchema), NULL)
#18 /var/www/wpkg/lib/Cake/Console/Shell.php(459): SchemaShell->create()
#19 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('create', Array)
#20 /var/www/wpkg/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#21 /var/www/wpkg/app/Plugin/CakeInstaller/Console/Command/CakeInstallerShell.php(649): Shell->dispatchShell('schema create -...')
#22 [internal function]: CakeInstallerShell->_createdb()
#23 /var/www/wpkg/app/Plugin/CakeInstaller/Console/Command/CakeInstallerShell.php(250): call_user_func(Array)
#24 /var/www/wpkg/lib/Cake/Console/Shell.php(462): CakeInstallerShell->main()
#25 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand(NULL, Array)
#26 /var/www/wpkg/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#27 /var/www/wpkg/app/Console/cake.php(47): ShellDispatcher::run(Array)
#28 {main}
```

Running Centos 7 with:

- PHP 5.6.40
- mysql  Ver 15.1 Distrib 5.5.64-MariaDB

**Comment by anklimsk** [comment]
Good day. Fixed in a new release: [v1.0.11](https://github.com/anklimsk/wpkg-express-2/releases/tag/v1.0.11)
